version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

builds:
  os: ubuntu-22.04
  tools:
    python: "3.8"