name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff
        pip install -e ".[dev]"
        
    - name: Check formatting with Black
      run: black --check --diff .
        
    - name: Lint with Ruff
      run: ruff check . --output-format=github

  test:
    name: Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
        include:
          # Test multiple Python versions on Ubuntu only
          - os: ubuntu-latest
            python-version: '3.10'
          - os: ubuntu-latest
            python-version: '3.12'
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e ".[dev]"
        
    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=term-missing --cov-report=xml -v
        
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  # Test MCP components separately (optional - more thorough)
  test-mcp:
    name: Test MCP Components
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install with MCP extras
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e ".[mcp,dev]"
        
    - name: Test MCP functionality
      run: |
        python -c "import napistu.mcp; print(f'MCP available: {napistu.mcp.is_available}')"
        pytest tests/ -k "mcp" -v || echo "No MCP tests found"